#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║  🎓 COURSES AFTER 10th IN INDIA — COMPLETE CAREER TREE 🇮🇳                ║
║  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  ║
║  Har ek possible path — with Time, Fees, Salary, Entrance Exams            ║
║  Language: Hinglish (Hindi + English mix)                                   ║
║  Author: Krishna1k (Generated by Kiro)                                     ║
╚══════════════════════════════════════════════════════════════════════════════╝

LEGEND:
  ⏱️  = Kitna time lagega (Duration)
  💰 = Kitne paise lagenge — Govt college | Private college
  💼 = Starting salary (freshers)
  📈 = Experienced salary (5-10 saal baad)
  🎯 = Entrance exam / eligibility
  🏫 = Top colleges
  🔥 = Scope / demand level
"""

def print_header():
    print("""
╔══════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                      ║
║   🎓🎓🎓  10th KE BAAD COMPLETE CAREER TREE — INDIA 2025  🎓🎓🎓                   ║
║                                                                                      ║
║   Ye file padh le bhai — tera pura future ka map hai                                 ║
║                                                                                      ║
╚══════════════════════════════════════════════════════════════════════════════════════╝

📌 SYMBOLS:
   ⏱️  = Time duration
   💰 = Fees (Govt | Private)
   💼 = Starting Salary
   📈 = 5-10 saal baad salary
   🎯 = Entrance Exam
   🏫 = Top Colleges
   🔥 = Demand/Scope (⭐ to ⭐⭐⭐⭐⭐)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")



def print_main_tree():
    print("""
┌─────────────────────────────────────────────────────────────────┐
│                    📚 10th PASS (Board Result Aaya)              │
└───────────────────────────────────┬─────────────────────────────┘
                                    │
        ┌───────────┬───────────┬───┴───┬───────────┬───────────┬──────────┐
        │           │           │       │           │           │          │
   ┌────┴────┐ ┌───┴───┐ ┌────┴───┐ ┌─┴──┐  ┌────┴────┐ ┌───┴───┐ ┌───┴────┐
   │ 11-12th │ │DIPLOMA│ │  ITI   │ │ARMY│  │VOCATIO- │ │ OPEN  │ │SPORTS/ │
   │Academic │ │Polytec│ │(Skill) │ │NAVY│  │  NAL    │ │SCHOOL │ │SELF-EMP│
   └────┬────┘ └───┬───┘ └────┬───┘ └─┬──┘  └────┬────┘ └───┬───┘ └───┬────┘
        │           │          │       │           │          │         │
   [Section 1] [Section 2] [Sec 3] [Sec 4]   [Sec 5]    [Sec 6]   [Sec 7]
""")



def print_section_1_science():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔬 SECTION 1: ACADEMIC PATH — 11th & 12th (10+2)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  11th-12th mein 3 main streams hain:
  ├── 🔬 SCIENCE (PCM / PCB / PCMB)
  ├── 💹 COMMERCE (with Maths / without Maths)
  └── 📖 ARTS / HUMANITIES


══════════════════════════════════════════════════════════
⚙️  1A) SCIENCE — PCM (Physics + Chemistry + Maths)
══════════════════════════════════════════════════════════

  PCM lene ke baad ye sab options khulte hain:
  │
  ├── 🖥️  B.TECH / B.E (ENGINEERING)
  │   │
  │   ├── 💻 Computer Science & Engineering (CSE)
  │   │      ⏱️  4 saal (8 semesters)
  │   │      💰 Govt: ₹2-8 Lakh total | Pvt: ₹8-20 Lakh total
  │   │      🎯 JEE Main → NITs, IIITs | JEE Advanced → IITs
  │   │      💼 Starting: ₹6-25 Lakh/year (IIT/NIT se zyada)
  │   │      📈 5-10 yrs: ₹20-60 Lakh/year (FAANG = ₹50L-2Cr+)
  │   │      🏫 IIT Bombay, IIT Delhi, IIT Madras, BITS Pilani, NIT Trichy
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Sabse zyada demand India mein)
  │   │
  │   ├── 🤖 Artificial Intelligence & Machine Learning
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹3-8L | Pvt: ₹10-20L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹8-30 Lakh/year
  │   │      📈 5-10 yrs: ₹25-80 Lakh/year (research = ₹1Cr+)
  │   │      🏫 IIT Hyderabad, IIT Madras, IIIT Hyderabad
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Future ka king — har jagah AI chahiye)
  │   │
  │   ├── 📊 Data Science & Analytics
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-8L | Pvt: ₹10-18L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹6-20 Lakh/year
  │   │      📈 5-10 yrs: ₹18-50 Lakh/year
  │   │      🏫 IIT Madras, ISI Kolkata, IIIT Hyderabad
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   ├── 📡 Electronics & Communication (ECE)
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-6L | Pvt: ₹6-15L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹4-12 Lakh/year
  │   │      📈 5-10 yrs: ₹12-35 Lakh/year
  │   │      🏫 IIT Delhi, IIT Bombay, NIT Surathkal
  │   │      🔥 Demand: ⭐⭐⭐⭐ (VLSI, Embedded systems hot)
  │   │
  │   ├── ⚡ Electrical Engineering (EEE)
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-6L | Pvt: ₹6-15L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹4-10 Lakh/year
  │   │      📈 5-10 yrs: ₹10-30 Lakh/year
  │   │      🏫 IIT Kharagpur, IIT Kanpur, NIT Warangal
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Power sector + EV boom)
  │   │
  │   ├── 🔧 Mechanical Engineering
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-6L | Pvt: ₹6-15L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹3.5-8 Lakh/year
  │   │      📈 5-10 yrs: ₹10-25 Lakh/year
  │   │      🏫 IIT Bombay, IIT Kanpur, BITS Pilani
  │   │      🔥 Demand: ⭐⭐⭐ (Traditional but stable)
  │   │
  │   ├── 🏗️  Civil Engineering
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-5L | Pvt: ₹5-12L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹3-6 Lakh/year
  │   │      📈 5-10 yrs: ₹8-20 Lakh/year (own firm = more)
  │   │      🏫 IIT Roorkee, IIT Madras, NIT Surat
  │   │      🔥 Demand: ⭐⭐⭐ (Infra boom se badh raha)
  │   │
  │   ├── 🧪 Chemical Engineering
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-5L | Pvt: ₹5-12L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹5-10 Lakh/year
  │   │      📈 5-10 yrs: ₹12-30 Lakh/year
  │   │      🏫 IIT Bombay, ICT Mumbai, BITS Pilani
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Pharma + Oil sector)
  │   │
  │   ├── ✈️  Aerospace / Aeronautical Engineering
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-8L | Pvt: ₹8-18L
  │   │      🎯 JEE Advanced (IIT Bombay/Madras), IIST entrance
  │   │      💼 Starting: ₹6-15 Lakh/year
  │   │      📈 5-10 yrs: ₹15-40 Lakh/year (ISRO, DRDO, HAL)
  │   │      🏫 IIT Bombay, IIT Madras, IIST Trivandrum
  │   │      🔥 Demand: ⭐⭐⭐⭐ (India ka space program boom)
  │   │
  │   ├── 🧬 Biotechnology
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-6L | Pvt: ₹6-15L
  │   │      🎯 JEE/GATE/ICAR
  │   │      💼 Starting: ₹3-7 Lakh/year
  │   │      📈 5-10 yrs: ₹8-25 Lakh/year
  │   │      🏫 IIT Delhi, IIT Madras, ICT Mumbai
  │   │      🔥 Demand: ⭐⭐⭐ (Pharma/Biotech growing)
  │   │
  │   ├── 🤖 Robotics & Mechatronics
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹3-8L | Pvt: ₹8-18L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹5-15 Lakh/year
  │   │      📈 5-10 yrs: ₹15-40 Lakh/year
  │   │      🏫 IIT Delhi, BITS Pilani, MIT Manipal
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Automation ka future)
  │   │
  │   ├── 🛢️  Petroleum / Mining / Marine Engineering
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-5L | Pvt: ₹5-12L
  │   │      🎯 JEE/IMU CET (Marine)
  │   │      💼 Starting: ₹5-12 Lakh/year
  │   │      📈 5-10 yrs: ₹15-40 Lakh/year (overseas = more)
  │   │      🏫 ISM Dhanbad, IIT(ISM), IMU
  │   │      🔥 Demand: ⭐⭐⭐
  │   │
  │   ├── 🌐 Information Technology (IT)
  │   │      ⏱️  4 saal
  │   │      💰 Govt: ₹2-8L | Pvt: ₹8-18L
  │   │      🎯 JEE Main/Advanced
  │   │      💼 Starting: ₹5-18 Lakh/year
  │   │      📈 5-10 yrs: ₹15-45 Lakh/year
  │   │      🏫 IITs, NITs, IIIT Hyderabad, DTU
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   └── 🔒 Cybersecurity / Ethical Hacking (B.Tech specialization)
  │          ⏱️  4 saal
  │          💰 Govt: ₹3-8L | Pvt: ₹10-20L
  │          🎯 JEE + specialization
  │          💼 Starting: ₹6-18 Lakh/year
  │          📈 5-10 yrs: ₹20-60 Lakh/year
  │          🏫 IITs, IIIT Delhi, Amrita
  │          🔥 Demand: ⭐⭐⭐⭐⭐ (Cybercrime badhne se demand boom)
""")



def print_section_1_science_continued():
    print("""
  │
  ├── 🏛️  B.ARCH (Architecture)
  │      ⏱️  5 saal (10 semesters — sabse lamba UG course)
  │      💰 Govt: ₹2-5 Lakh total | Pvt: ₹8-20 Lakh total
  │      🎯 NATA + JEE Main Paper 2
  │      💼 Starting: ₹3-8 Lakh/year
  │      📈 5-10 yrs: ₹12-30 Lakh/year (apna firm = ₹50L+)
  │      🏫 IIT Kharagpur, IIT Roorkee, SPA Delhi, CEPT Ahmedabad
  │      🔥 Demand: ⭐⭐⭐⭐ (Smart cities + real estate)
  │
  ├── 🎓 B.Sc (Bachelor of Science)
  │   │
  │   ├── B.Sc Physics
  │   │      ⏱️  3 saal | 💰 ₹15-50K (Govt) | ₹1-5L (Pvt)
  │   │      💼 ₹3-5L/yr | 📈 ₹8-20L/yr (research/professor)
  │   │      🎯 Merit / CUET | 🏫 St. Stephens, Hindu, Presidency
  │   │
  │   ├── B.Sc Mathematics
  │   │      ⏱️  3 saal | 💰 ₹15-50K | ₹1-4L
  │   │      💼 ₹3-6L/yr | 📈 ₹10-30L/yr (data science/quant)
  │   │      🎯 CUET / Merit | 🏫 ISI Kolkata, CMI Chennai, St. Stephens
  │   │
  │   ├── B.Sc Chemistry
  │   │      ⏱️  3 saal | 💰 ₹15-50K | ₹1-4L
  │   │      💼 ₹3-5L/yr | 📈 ₹8-18L/yr (pharma/research)
  │   │
  │   ├── B.Sc Computer Science
  │   │      ⏱️  3 saal | 💰 ₹20K-1L | ₹2-8L
  │   │      💼 ₹4-10L/yr | 📈 ₹12-35L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Coding = paisa)
  │   │
  │   ├── B.Sc Statistics
  │   │      ⏱️  3 saal | 💰 ₹15-50K | ₹1-5L
  │   │      💼 ₹4-8L/yr | 📈 ₹15-40L/yr (data analyst/actuary)
  │   │      🏫 ISI Kolkata (best), St. Xaviers
  │   │
  │   └── B.Sc Electronics / Instrumentation
  │          ⏱️  3 saal | 💰 ₹20-60K | ₹2-6L
  │          💼 ₹3-6L/yr | 📈 ₹8-20L/yr
  │
  ├── 💻 BCA (Bachelor of Computer Applications)
  │      ⏱️  3 saal
  │      💰 Govt: ₹30K-2L | Pvt: ₹2-6L
  │      🎯 Class 12 pass (kuch jagah entrance)
  │      💼 Starting: ₹3-6 Lakh/year
  │      📈 5-10 yrs: ₹8-25 Lakh/year (skills pe depend)
  │      🏫 Christ Bangalore, Symbiosis, JNU
  │      🔥 Demand: ⭐⭐⭐⭐ (Coding without engineering)
  │
  ├── 🚀 INTEGRATED M.Sc (5 year — Bachelor + Master combined)
  │      ⏱️  5 saal
  │      💰 Govt: ₹2-5L total (scholarship milta)
  │      🎯 IIT JAM, IISER Aptitude Test, NEST, KVPY
  │      💼 Starting: ₹5-12L/yr (research) | 📈 ₹15-40L/yr
  │      🏫 IISERs, NISER, IITs, Central Unis
  │      🔥 Demand: ⭐⭐⭐⭐ (PhD + Research track)
  │
  ├── ✈️  PILOT (Commercial Pilot License — CPL)
  │      ⏱️  2-3 saal training
  │      💰 ₹25-40 Lakh total (bahut mehenga!)
  │      🎯 DGCA exams + medical fitness + flying hours
  │      💼 Starting: ₹10-15 Lakh/year (co-pilot)
  │      📈 Captain: ₹30-80 Lakh/year (international = ₹1Cr+)
  │      🏫 Indira Gandhi Rashtriya Udan Academy, private schools
  │      🔥 Demand: ⭐⭐⭐⭐ (airlines expand ho rahi)
  │
  ├── 🚢 MERCHANT NAVY (B.Sc Nautical Science / Marine Engg)
  │      ⏱️  3-4 saal
  │      💰 Govt: ₹3-8L | Pvt: ₹10-20L
  │      🎯 IMU CET / Direct admission
  │      💼 Starting: ₹8-15 Lakh/year
  │      📈 Captain/Chief Engineer: ₹50L-1.5 Crore/year! 🤑
  │      🏫 IMU (Indian Maritime University), MERI Mumbai
  │      🔥 Demand: ⭐⭐⭐⭐ (Tax-free salary + world travel)
  │
  ├── 🎨 B.DESIGN / B.DES
  │      ⏱️  4 saal
  │      💰 Govt: ₹3-8L | Pvt: ₹8-20L
  │      🎯 UCEED (IITs), NID DAT, NIFT, CEED
  │      💼 Starting: ₹5-12 Lakh/year
  │      📈 5-10 yrs: ₹15-40 Lakh/year (UX/UI = ₹50L+)
  │      🏫 NID Ahmedabad, IIT Bombay IDC, NIFT Delhi
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (UX/UI designers ki zaroorat har jagah)
  │
  └── 🛡️  NDA (National Defence Academy) — PCM se entry
         ⏱️  3 saal NDA + 1 saal training = 4 saal total
         💰 FREE (Govt pays you — stipend milta hai!)
         🎯 NDA Exam (UPSC) after 12th + SSB Interview
         💼 Starting: ₹60,000-80,000/month (Lieutenant)
         📈 Colonel+: ₹2-3 Lakh/month + perks worth crores
         🏫 NDA Khadakwasla (Pune), then IMA/AFA/INA
         🔥 Demand: ⭐⭐⭐⭐⭐ (Izzat + Paisa + Desh Seva)
""")



def print_section_1_pcb():
    print("""
══════════════════════════════════════════════════════════
🧬 1B) SCIENCE — PCB (Physics + Chemistry + Biology)
══════════════════════════════════════════════════════════

  PCB lene ke baad ye sab options khulte hain:
  │
  ├── 🏥 MBBS (Allopathy Doctor — sabse popular choice)
  │      ⏱️  5.5 saal (4.5 yrs study + 1 yr internship)
  │      💰 Govt: ₹2-10 Lakh total | Pvt: ₹50L-1.5 Crore 😱
  │      🎯 NEET UG (only exam — no other option!)
  │      💼 Starting: ₹6-12 Lakh/year (after internship)
  │      📈 Specialist (MD/MS): ₹20-60L/yr | Super-specialist: ₹1-3 Crore/yr
  │      🏫 AIIMS Delhi, JIPMER, CMC Vellore, MAMC Delhi, KEM Mumbai
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Doctor = permanent respect + income)
  │      ⚠️  Note: NEET bahut competitive — 20 lakh students dete hain
  │
  ├── 🦷 BDS (Bachelor of Dental Surgery)
  │      ⏱️  5 saal (4 yrs + 1 yr internship)
  │      💰 Govt: ₹2-5L | Pvt: ₹20-60L
  │      🎯 NEET UG
  │      💼 Starting: ₹4-8 Lakh/year
  │      📈 Own clinic: ₹15-50 Lakh/year
  │      🏫 Maulana Azad, Manipal, SRM
  │      🔥 Demand: ⭐⭐⭐ (Cosmetic dentistry growing)
  │
  ├── 🌿 BAMS (Ayurveda Doctor)
  │      ⏱️  5.5 saal (4.5 + 1 internship)
  │      💰 Govt: ₹1-3L | Pvt: ₹10-30L
  │      🎯 NEET UG
  │      💼 Starting: ₹3-6 Lakh/year
  │      📈 Own practice: ₹10-30L/yr
  │      🔥 Demand: ⭐⭐⭐ (Ayurveda boom globally)
  │
  ├── 💊 BHMS (Homeopathy Doctor)
  │      ⏱️  5.5 saal
  │      💰 Govt: ₹1-3L | Pvt: ₹8-25L
  │      🎯 NEET UG
  │      💼 Starting: ₹2.5-5 Lakh/year
  │      📈 Own clinic: ₹8-25L/yr
  │      🔥 Demand: ⭐⭐⭐
  │
  ├── 🧘 BNYS (Naturopathy & Yoga)
  │      ⏱️  5.5 saal
  │      💰 Govt: ₹1-2L | Pvt: ₹5-15L
  │      🎯 NEET UG
  │      💼 Starting: ₹2-4 Lakh/year
  │      📈 ₹8-20L/yr (wellness industry)
  │      🔥 Demand: ⭐⭐⭐ (Yoga trend + wellness boom)
  │
  ├── 🧴 BUMS (Unani Medicine)
  │      ⏱️  5.5 saal | 💰 Govt: ₹1-3L | Pvt: ₹5-20L
  │      🎯 NEET UG | 💼 ₹2.5-5L/yr | 📈 ₹8-20L/yr
  │
  ├── 💊 B.Pharma (Pharmacy)
  │      ⏱️  4 saal
  │      💰 Govt: ₹1-4L | Pvt: ₹4-12L
  │      🎯 State CET / WBJEE / Direct
  │      💼 Starting: ₹3-6 Lakh/year
  │      📈 5-10 yrs: ₹8-25L/yr (pharma companies = ₹30L+)
  │      🏫 NIPER, ICT Mumbai, JSS Mysore, Manipal
  │      🔥 Demand: ⭐⭐⭐⭐ (India = pharmacy capital of world)
  │
  ├── 👩‍⚕️ B.Sc NURSING
  │      ⏱️  4 saal
  │      💰 Govt: ₹30K-2L | Pvt: ₹2-8L
  │      🎯 NEET / State nursing entrance
  │      💼 Starting: ₹3-5 Lakh/year (India) | Abroad: ₹15-30L/yr!
  │      📈 Senior Nurse: ₹8-15L/yr (India) | ₹40-80L/yr (US/UK/Gulf)
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Worldwide shortage — golden ticket abroad!)
  │
  ├── 🏃 BPT (Physiotherapy)
  │      ⏱️  4.5 saal (4 + 6 month internship)
  │      💰 Govt: ₹1-3L | Pvt: ₹4-12L
  │      🎯 State CET / NEET (some states)
  │      💼 Starting: ₹3-5 Lakh/year
  │      📈 Own clinic: ₹10-30L/yr | Sports physio: ₹20-50L/yr
  │      🔥 Demand: ⭐⭐⭐⭐ (Sports + fitness culture growing)
  │
  ├── 🐮 B.V.Sc (Veterinary Science — Animal Doctor)
  │      ⏱️  5.5 saal (5 + 6 months internship)
  │      💰 Govt: ₹1-3L | Pvt: ₹5-15L
  │      🎯 NEET UG (separate counseling)
  │      💼 Starting: ₹4-7 Lakh/year
  │      📈 ₹10-25L/yr (pet industry booming)
  │      🔥 Demand: ⭐⭐⭐⭐ (Pet parents = growing market)
  │
  ├── 👁️  B.Optometry (Eye specialist — non-doctor)
  │      ⏱️  4 saal | 💰 ₹1-3L (Govt) | ₹3-10L (Pvt)
  │      💼 ₹3-5L/yr | 📈 ₹8-20L/yr (own clinic = more)
  │
  ├── 🌾 B.Sc AGRICULTURE
  │      ⏱️  4 saal
  │      💰 Govt: ₹50K-2L | Pvt: ₹2-8L
  │      🎯 ICAR AIEEA / State CET
  │      💼 Starting: ₹3-6L/yr (Govt jobs bhi milte)
  │      📈 ₹8-20L/yr (agritech startups = ₹30L+)
  │      🏫 IARI Delhi, PAU Ludhiana, TNAU Coimbatore
  │      🔥 Demand: ⭐⭐⭐⭐ (Agritech + organic farming boom)
  │
  ├── 🌲 B.Sc Forestry
  │      ⏱️  4 saal | 💰 Govt: ₹50K-2L | Pvt: ₹2-6L
  │      🎯 ICAR | 💼 ₹3-5L/yr | 📈 IFS officer: ₹15-30L/yr
  │
  ├── 🧫 B.Sc Microbiology / Biotech / Genetics
  │      ⏱️  3 saal | 💰 Govt: ₹30K-1L | Pvt: ₹2-6L
  │      💼 ₹3-5L/yr | 📈 ₹8-25L/yr (pharma research)
  │      🔥 Demand: ⭐⭐⭐ (COVID ke baad awareness badhi)
  │
  └── 🔬 B.Sc MLT (Medical Lab Technology)
         ⏱️  3 saal | 💰 Govt: ₹30K-1L | Pvt: ₹2-5L
         💼 ₹2.5-4L/yr | 📈 ₹6-15L/yr
         🔥 Demand: ⭐⭐⭐⭐ (Labs har jagah chahiye)
""")



def print_section_1_commerce():
    print("""
══════════════════════════════════════════════════════════
💹 1C) COMMERCE STREAM
══════════════════════════════════════════════════════════

  Commerce lene ke baad ye options hain:
  │
  ├── 📊 CA (Chartered Accountant) — 🏆 COMMERCE KA KING
  │      ⏱️  5 saal minimum (Foundation → Inter → Final)
  │      💰 Total: ₹1-2 Lakh (bahut sasta course!)
  │      🎯 CA Foundation (after 12th) → CA Inter → CA Final + Articleship
  │      💼 Starting: ₹7-12 Lakh/year (Big 4 = ₹15-20L)
  │      📈 5-10 yrs: ₹25-60L/yr | Partner: ₹1-5 Crore/yr
  │      🏫 ICAI (Institute of Chartered Accountants of India)
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Har company ko CA chahiye)
  │      ⚠️  Note: Pass rate sirf 5-10% — bahut mushkil but bahut rewarding
  │
  ├── 📋 CS (Company Secretary)
  │      ⏱️  4-5 saal (Foundation → Executive → Professional)
  │      💰 Total: ₹50K-1.5L
  │      🎯 CSEET (after 12th)
  │      💼 Starting: ₹5-8 Lakh/year
  │      📈 5-10 yrs: ₹15-40L/yr | Own practice: ₹50L+
  │      🏫 ICSI (Institute of Company Secretaries)
  │      🔥 Demand: ⭐⭐⭐⭐ (Corporate governance + compliance)
  │
  ├── 🧮 CMA (Cost & Management Accountant)
  │      ⏱️  4-5 saal
  │      💰 Total: ₹50K-1L
  │      🎯 CMA Foundation after 12th
  │      💼 Starting: ₹5-8L/yr | 📈 ₹15-35L/yr
  │      🏫 ICMAI | 🔥 Demand: ⭐⭐⭐⭐
  │
  ├── 📚 B.COM (Bachelor of Commerce)
  │   │
  │   ├── B.Com (Hons)
  │   │      ⏱️  3 saal | 💰 Govt: ₹10-30K | Pvt: ₹1-5L
  │   │      🎯 CUET / Merit / DU Entrance
  │   │      💼 ₹3-5L/yr | 📈 ₹8-20L/yr
  │   │      🏫 SRCC Delhi, Hindu College, Christ Bangalore
  │   │
  │   ├── B.Com + CA (Best combo — most students do this)
  │   │      ⏱️  3+2 saal parallel | Kharcha minimal
  │   │      💼 After CA: ₹8-20L/yr immediately
  │   │
  │   └── B.Com in Banking & Insurance
  │          ⏱️  3 saal | 💰 ₹1-5L | 💼 ₹3-5L/yr | 📈 ₹8-20L/yr
  │
  ├── 🏢 BBA / BMS (Business Administration / Management Studies)
  │      ⏱️  3 saal
  │      💰 Govt: ₹50K-2L | Pvt: ₹3-10L
  │      🎯 CUET / IPMAT (IIM) / SET / Christ Entrance
  │      💼 Starting: ₹4-8 Lakh/year
  │      📈 After MBA: ₹15-50L/yr (IIM = ₹25-50L)
  │      🏫 IIM Indore (IPM), Shaheed Sukhdev, Christ, Symbiosis
  │      🔥 Demand: ⭐⭐⭐⭐ (MBA ki seedhi tayyari)
  │
  ├── ⚖️  BBA-LLB (Integrated Law — 5 years)
  │      ⏱️  5 saal
  │      💰 Govt (NLU): ₹5-10L | Pvt: ₹10-25L
  │      🎯 CLAT / AILET / LSAT
  │      💼 Starting: ₹8-15L/yr (top NLU)
  │      📈 Senior Lawyer: ₹30L-2Cr/yr | Corporate: ₹50L+
  │      🏫 NLSIU Bangalore, NALSAR Hyderabad, NLU Delhi
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Corporate law = big money)
  │
  ├── 💰 CFA (Chartered Financial Analyst)
  │      ⏱️  2-4 saal (3 levels — can start after graduation)
  │      💰 ₹3-5 Lakh (US-based exam)
  │      💼 ₹8-15L/yr | 📈 ₹25-80L/yr (global finance)
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Investment banking + hedge funds)
  │
  ├── 📈 BFIA / BBE (Finance & Investment / Business Economics)
  │      ⏱️  3 saal | 💰 ₹50K-3L
  │      💼 ₹4-7L/yr | 📈 ₹12-30L/yr (after CFA/MBA)
  │      🏫 Shaheed Sukhdev CBS, DU colleges
  │
  ├── 🏨 BHM (Hotel Management)
  │      ⏱️  4 saal
  │      💰 Govt (IHM): ₹3-5L | Pvt: ₹6-15L
  │      🎯 NCHMCT JEE
  │      💼 Starting: ₹3-6L/yr | 📈 GM level: ₹20-50L/yr
  │      🏫 IHM Pusa Delhi, IHM Mumbai
  │      🔥 Demand: ⭐⭐⭐⭐ (Tourism + 5-star chains growing)
  │
  ├── 📱 DIGITAL MARKETING (Certificate/Diploma — short term)
  │      ⏱️  3-6 months
  │      💰 ₹20K-1L (online courses)
  │      💼 Starting: ₹3-6L/yr (freelance = ₹10L+)
  │      📈 ₹10-30L/yr | Own agency: ₹50L+
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Har business ko digital marketing chahiye!)
  │
  └── 🎉 EVENT MANAGEMENT
         ⏱️  3 saal (degree) / 1 yr (diploma)
         💰 ₹2-8L | 💼 ₹3-5L/yr | 📈 Own company: ₹20-50L+
         🔥 Demand: ⭐⭐⭐⭐ (Weddings + corporate events booming)
""")



def print_section_1_arts():
    print("""
══════════════════════════════════════════════════════════
📖 1D) ARTS / HUMANITIES STREAM
══════════════════════════════════════════════════════════

  Arts liya? Mat soch ki scope nahi — dekh ye options:
  │
  ├── 📚 BA (Bachelor of Arts — so many subjects!)
  │   │
  │   ├── BA English Literature
  │   │      ⏱️  3 saal | 💰 ₹10-30K (Govt) | ₹1-5L (Pvt)
  │   │      💼 ₹3-5L/yr | 📈 Content/Journalist: ₹10-25L/yr
  │   │
  │   ├── BA Political Science
  │   │      ⏱️  3 saal | 💰 ₹10-30K | ₹1-3L
  │   │      💼 ₹3-4L/yr | 📈 After UPSC: ₹15-30L/yr + perks
  │   │      🔥 Best for UPSC preparation!
  │   │
  │   ├── BA History
  │   │      ⏱️  3 saal | 💰 ₹10-30K | 💼 ₹2.5-4L/yr
  │   │      📈 After UPSC/NET: ₹12-25L/yr
  │   │
  │   ├── BA Psychology
  │   │      ⏱️  3 saal | 💰 ₹15-50K | ₹2-6L
  │   │      💼 ₹3-5L/yr | 📈 Clinical Psychologist: ₹10-30L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Mental health awareness UP!)
  │   │
  │   ├── BA Economics
  │   │      ⏱️  3 saal | 💰 ₹15-50K | ₹1-5L
  │   │      💼 ₹4-8L/yr | 📈 Economist/Analyst: ₹15-50L/yr
  │   │      🏫 Delhi School of Economics, JNU, Presidency
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Finance + policy = big money)
  │   │
  │   ├── BA Geography / Sociology / Philosophy
  │   │      ⏱️  3 saal | 💰 ₹10-30K
  │   │      💼 ₹2.5-4L/yr | 📈 ₹8-18L/yr (teaching/research)
  │   │
  │   └── BA Foreign Languages (French/German/Japanese/Spanish)
  │          ⏱️  3 saal | 💰 ₹20K-2L
  │          💼 ₹4-8L/yr | 📈 Translator/MNC: ₹10-30L/yr
  │          🏫 JNU, EFL Hyderabad, BHU
  │          🔥 Demand: ⭐⭐⭐⭐ (MNCs mein high demand)
  │
  ├── ⚖️  BA-LLB (5 Year Integrated Law) — 🏆 ARTS KA BEST OPTION
  │      ⏱️  5 saal
  │      💰 NLU (Govt): ₹5-10L total | Pvt: ₹10-25L
  │      🎯 CLAT / AILET / LSAT India
  │      💼 Starting: ₹8-15L/yr (top NLU) | Tier-2: ₹5-8L/yr
  │      📈 Senior Advocate: ₹50L-5 Crore/yr | Judge: ₹2-3L/month
  │      🏫 NLSIU Bangalore (#1), NALSAR, NLU Delhi, NUJS Kolkata
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (Corporate law firms pay like IT!)
  │
  ├── 📺 BJMC (Journalism & Mass Communication)
  │      ⏱️  3-4 saal
  │      💰 Govt: ₹50K-2L | Pvt: ₹3-10L
  │      🎯 CUET / IIMC Entrance / IPU CET
  │      💼 Starting: ₹3-6L/yr
  │      📈 Senior Editor/Anchor: ₹15-50L/yr | Own channel: unlimited
  │      🏫 IIMC Delhi, Symbiosis, ACJ Chennai, Xavier's Mumbai
  │      🔥 Demand: ⭐⭐⭐⭐ (Digital media explosion)
  │
  ├── 👩‍🏫 B.Ed (Bachelor of Education — Teacher banna)
  │      ⏱️  2 saal (after graduation) / 4 yrs integrated
  │      💰 Govt: ₹20-50K | Pvt: ₹50K-2L
  │      🎯 State B.Ed entrance
  │      💼 Starting: ₹3-5L/yr (Pvt school) | Govt: ₹5-8L/yr
  │      📈 PGT/Senior Teacher: ₹8-15L/yr | Professor: ₹15-25L/yr
  │      🔥 Demand: ⭐⭐⭐⭐ (Teaching jobs never die)
  │
  ├── 🎨 BFA (Fine Arts — Painting, Sculpture, Photography)
  │      ⏱️  4 saal
  │      💰 Govt: ₹20-50K | Pvt: ₹2-8L
  │      🎯 Entrance drawing test + portfolio
  │      💼 Starting: ₹2-5L/yr
  │      📈 Established artist: ₹10-50L/yr | Commercial: ₹8-25L
  │      🏫 JJ School Mumbai, BHU, MSU Baroda
  │      🔥 Demand: ⭐⭐⭐ (Niche but passionate — NFTs bhi!)
  │
  ├── 🎭 BPA (Performing Arts — Music, Dance, Theatre)
  │      ⏱️  3-4 saal
  │      💰 Govt: ₹20K-1L | Pvt: ₹2-6L
  │      💼 ₹2-5L/yr | 📈 Famous artist: unlimited
  │      🏫 NSD (Theatre), SRFTI, Film institutes
  │
  ├── 👗 FASHION DESIGN (NIFT / NID)
  │      ⏱️  4 saal
  │      💰 Govt (NIFT): ₹5-8L total | Pvt: ₹8-20L
  │      🎯 NIFT Entrance / NID DAT / UCEED
  │      💼 Starting: ₹4-8L/yr
  │      📈 Senior Designer: ₹15-40L/yr | Own brand: Crores
  │      🏫 NIFT Delhi, NID Ahmedabad, Pearl Academy
  │      🔥 Demand: ⭐⭐⭐⭐ (Fashion industry = ₹5 lakh crore)
  │
  ├── 🏠 INTERIOR DESIGN
  │      ⏱️  4 saal (degree) / 1-2 yr (diploma)
  │      💰 ₹2-10L | 💼 ₹3-6L/yr | 📈 Own firm: ₹15-50L/yr
  │      🔥 Demand: ⭐⭐⭐⭐ (Real estate = interior demand)
  │
  ├── 🎬 ANIMATION & VFX
  │      ⏱️  3 saal (degree) / 1 yr (diploma)
  │      💰 ₹2-8L
  │      💼 Starting: ₹3-6L/yr
  │      📈 Senior Animator: ₹12-35L/yr | Hollywood: ₹50L+
  │      🏫 MAAC, Arena, Whistling Woods
  │      🔥 Demand: ⭐⭐⭐⭐⭐ (OTT + Gaming = massive demand)
  │
  ├── 🌍 TRAVEL & TOURISM
  │      ⏱️  3 saal | 💰 ₹1-5L
  │      💼 ₹2.5-4L/yr | 📈 Travel company: ₹10-25L/yr
  │      🔥 Demand: ⭐⭐⭐⭐ (Post-COVID travel boom)
  │
  ├── 🤝 BSW (Social Work)
  │      ⏱️  3 saal | 💰 ₹10-50K (Govt)
  │      💼 ₹2.5-4L/yr | 📈 NGO head/CSR: ₹8-20L/yr
  │
  ├── 📚 LIBRARY SCIENCE (B.Lib.I.Sc)
  │      ⏱️  1 saal (after graduation)
  │      💰 ₹10-30K | 💼 ₹3-5L/yr | 📈 ₹6-12L/yr (Govt librarian)
  │
  └── 🏛️  UPSC / IAS / IPS (Koi bhi stream → Graduation → UPSC)
         ⏱️  Graduation (3 yr) + Prep (2-3 yr) = 5-6 saal after 12th
         💰 Coaching: ₹1-3L | Self-study possible too!
         🎯 UPSC CSE (toughest exam in India)
         💼 IAS Entry: ₹80K-1L/month + free house/car/staff
         📈 Secretary level: ₹2.5L/month + power worth crores
         🔥 Demand: ⭐⭐⭐⭐⭐ (Izzat + Power + Service + Salary)
         ⚠️  Pass rate: 0.1% — but life set for those who clear!
""")



def print_section_2_diploma():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔧 SECTION 2: DIPLOMA / POLYTECHNIC (Seedha 10th ke baad — 3 saal)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⭐ BENEFIT: 3 saal mein diploma → Lateral Entry se seedha B.Tech 2nd year!
  ⭐ Matlab: Diploma (3 yr) + B.Tech (3 yr) = Engineer in 6 yrs (same as normal!)
  ⭐ Kharcha kam, practical knowledge zyada

  │
  ├── ⚙️  ENGINEERING DIPLOMAS
  │   │
  │   ├── Diploma in Computer Engineering / IT
  │   │      ⏱️  3 saal | 💰 Govt: ₹15-40K/yr | Pvt: ₹50K-2L/yr
  │   │      💼 After diploma: ₹2-4L/yr | After B.Tech: ₹6-15L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   ├── Diploma in Mechanical Engineering
  │   │      ⏱️  3 saal | 💰 Govt: ₹15-40K/yr | Pvt: ₹40K-1.5L/yr
  │   │      💼 ₹2-3.5L/yr | 📈 After B.Tech: ₹5-12L/yr
  │   │      🔥 Demand: ⭐⭐⭐
  │   │
  │   ├── Diploma in Civil Engineering
  │   │      ⏱️  3 saal | 💰 Govt: ₹15-40K/yr | Pvt: ₹40K-1.5L/yr
  │   │      💼 ₹2-3L/yr | 📈 ₹5-12L/yr | Contractor: ₹20L+
  │   │      🔥 Demand: ⭐⭐⭐ (Infra projects)
  │   │
  │   ├── Diploma in Electrical Engineering
  │   │      ⏱️  3 saal | 💰 Govt: ₹15-40K/yr
  │   │      💼 ₹2-3.5L/yr | 📈 ₹5-15L/yr (power sector)
  │   │      🔥 Demand: ⭐⭐⭐⭐ (EV + Solar boom)
  │   │
  │   ├── Diploma in Electronics & Communication
  │   │      ⏱️  3 saal | 💰 Govt: ₹15-40K/yr
  │   │      💼 ₹2-3.5L/yr | 📈 ₹5-12L/yr
  │   │
  │   ├── Diploma in Automobile Engineering
  │   │      ⏱️  3 saal | 💰 ₹15-40K/yr (Govt)
  │   │      💼 ₹2-3.5L/yr | 📈 ₹6-15L/yr (EV companies)
  │   │      🔥 Demand: ⭐⭐⭐⭐ (EV revolution!)
  │   │
  │   ├── Diploma in Chemical / Textile / Plastic Engineering
  │   │      ⏱️  3 saal | 💰 ₹15-40K/yr
  │   │      💼 ₹2-3L/yr | 📈 ₹5-12L/yr
  │   │
  │   └── Diploma in Mining Engineering
  │          ⏱️  3 saal | 💰 ₹15-30K/yr (mostly Govt)
  │          💼 ₹2.5-4L/yr | 📈 ₹8-20L/yr (Coal India etc.)
  │
  ├── 🏥 PARAMEDICAL DIPLOMAS
  │   │
  │   ├── DMLT (Medical Lab Technology)
  │   │      ⏱️  2 saal | 💰 ₹20-60K/yr | 💼 ₹2-3L/yr | 📈 ₹5-10L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Pathology labs = massive growth)
  │   │
  │   ├── D.Pharma (Diploma in Pharmacy)
  │   │      ⏱️  2 saal | 💰 Govt: ₹30-80K/yr | Pvt: ₹1-3L/yr
  │   │      💼 ₹2-3.5L/yr | 📈 Own medical shop: ₹8-20L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Pharmacy license = lifelong income)
  │   │
  │   ├── GNM Nursing (General Nursing & Midwifery)
  │   │      ⏱️  3.5 saal | 💰 Govt: ₹20-50K/yr | Pvt: ₹1-3L/yr
  │   │      💼 India: ₹2.5-4L/yr | Abroad: ₹15-30L/yr!
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Worldwide shortage!)
  │   │
  │   ├── ANM Nursing (Auxiliary Nurse Midwife)
  │   │      ⏱️  2 saal | 💰 ₹20-50K/yr | 💼 ₹1.8-3L/yr | 📈 ₹4-8L/yr
  │   │
  │   ├── X-Ray / Radiology Technician
  │   │      ⏱️  2 saal | 💰 ₹30-80K/yr | 💼 ₹2-3.5L/yr
  │   │
  │   ├── Dialysis Technician
  │   │      ⏱️  2 saal | 💰 ₹50K-1.5L/yr | 💼 ₹2.5-4L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Kidney patients badh rahe)
  │   │
  │   ├── ECG Technician
  │   │      ⏱️  1-2 saal | 💰 ₹30-60K | 💼 ₹2-3L/yr
  │   │
  │   └── DOT (Operation Theatre Technology)
  │          ⏱️  2 saal | 💰 ₹40K-1L/yr | 💼 ₹2.5-4L/yr
  │
  ├── 🎨 DESIGN & CREATIVE DIPLOMAS
  │   │
  │   ├── Fashion Designing
  │   │      ⏱️  1-3 saal | 💰 ₹1-5L | 💼 ₹2.5-5L/yr | 📈 Own brand: unlimited
  │   │
  │   ├── Interior Designing
  │   │      ⏱️  1-2 saal | 💰 ₹1-4L | 💼 ₹2.5-5L/yr | 📈 ₹10-30L/yr
  │   │
  │   ├── Graphic Design
  │   │      ⏱️  1 saal | 💰 ₹50K-2L | 💼 ₹3-5L/yr | 📈 Freelance: ₹10-25L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   ├── Animation & VFX Diploma
  │   │      ⏱️  1-2 saal | 💰 ₹1-4L | 💼 ₹3-5L/yr | 📈 ₹10-30L/yr
  │   │
  │   ├── Photography Diploma
  │   │      ⏱️  6 months-1 yr | 💰 ₹50K-2L | 💼 ₹2-5L/yr
  │   │      📈 Wedding/Commercial: ₹10-30L/yr
  │   │
  │   └── Jewellery Design
  │          ⏱️  1-2 saal | 💰 ₹1-3L | 💼 ₹2.5-4L/yr | 📈 Own business: ₹10L+
  │
  ├── 🏨 HOTEL MANAGEMENT DIPLOMAS
  │   │
  │   ├── Diploma in Hotel Management
  │   │      ⏱️  1-2 saal | 💰 ₹1-4L | 💼 ₹2.5-4L/yr
  │   │      📈 5-star GM: ₹25-50L/yr
  │   │
  │   ├── Diploma in Culinary Arts (Chef)
  │   │      ⏱️  1-2 saal | 💰 ₹2-5L | 💼 ₹2.5-5L/yr
  │   │      📈 Head Chef (5-star): ₹15-40L/yr | Abroad: ₹40-80L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Food industry ka boom)
  │   │
  │   ├── Bakery & Confectionery
  │   │      ⏱️  6 months-1 yr | 💰 ₹50K-2L | 💼 ₹2-3L/yr
  │   │      📈 Own bakery: ₹8-25L/yr
  │   │
  │   └── Food & Beverage (F&B) Service
  │          ⏱️  1 yr | 💰 ₹50K-1.5L | 💼 ₹2-3.5L/yr
  │
  └── 🌾 AGRICULTURE & OTHER DIPLOMAS
      │
      ├── Agriculture Diploma
      │      ⏱️  2 saal | 💰 ₹20-60K | 💼 ₹2-3L/yr | 📈 Own farm: ₹5-15L/yr
      │
      ├── Horticulture
      │      ⏱️  2 saal | 💰 ₹20-50K | 💼 ₹2-3L/yr
      │
      ├── Dairy Technology
      │      ⏱️  2 saal | 💰 ₹30-80K | 💼 ₹2.5-4L/yr | 📈 Amul type: ₹8-20L/yr
      │
      ├── Fishery
      │      ⏱️  2 saal | 💰 ₹20-50K | 💼 ₹2-3L/yr
      │
      └── Cooperative Management
             ⏱️  2 saal | 💰 ₹20-50K | 💼 ₹2-3L/yr
""")



def print_section_3_iti():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛠️  SECTION 3: ITI (Industrial Training Institute — 6 months to 2 saal)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⭐ Sabse sasta aur sabse jaldi naukri dene wala course
  ⭐ Govt ITI = almost FREE (₹2-5K/year fees!)
  ⭐ Skills mil jaati — factory/industry mein seedha kaam
  ⭐ After ITI → can do Diploma Lateral Entry too!

  │
  ├── ⚡ ENGINEERING TRADES
  │   │
  │   ├── Electrician
  │   │      ⏱️  2 saal | 💰 Govt: ₹2-5K/yr (almost free!) | Pvt: ₹20-50K
  │   │      💼 Starting: ₹1.5-3L/yr | 📈 Own business: ₹5-15L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Har ghar, har factory ko electrician chahiye!)
  │   │
  │   ├── Fitter
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr (Govt)
  │   │      💼 ₹1.5-2.5L/yr | 📈 ₹4-8L/yr (Railways/PSU)
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Manufacturing sector)
  │   │
  │   ├── Welder
  │   │      ⏱️  1-2 saal | 💰 ₹2-5K/yr
  │   │      💼 ₹1.5-3L/yr | 📈 Underwater welder: ₹15-40L/yr! 🤑
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Construction + shipbuilding)
  │   │
  │   ├── Turner / Machinist
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr
  │   │      💼 ₹1.5-2.5L/yr | 📈 CNC operator: ₹4-10L/yr
  │   │
  │   ├── Mechanic (Diesel / Motor Vehicle)
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr
  │   │      💼 ₹1.5-3L/yr | 📈 Own garage: ₹5-15L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Gaadi toh sabko chahiye!)
  │   │
  │   ├── Plumber
  │   │      ⏱️  1-2 saal | 💰 ₹2-5K/yr
  │   │      💼 ₹1.5-2.5L/yr | 📈 ₹4-10L/yr (metro cities mein demand!)
  │   │
  │   ├── Refrigeration & AC Mechanic
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr
  │   │      💼 ₹2-3.5L/yr | 📈 ₹5-12L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (AC toh har ghar mein lagega ab!)
  │   │
  │   ├── Wireman
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr | 💼 ₹1.5-2.5L/yr
  │   │
  │   ├── Draughtsman (Civil / Mechanical)
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr
  │   │      💼 ₹2-3.5L/yr | 📈 CAD expert: ₹5-12L/yr
  │   │
  │   ├── Surveyor
  │   │      ⏱️  2 saal | 💰 ₹2-5K/yr | 💼 ₹2-3L/yr | 📈 ₹5-10L/yr
  │   │
  │   ├── COPA (Computer Operator & Programming Assistant)
  │   │      ⏱️  1 saal | 💰 ₹2-5K (Govt)
  │   │      💼 ₹1.5-3L/yr | 📈 ₹4-8L/yr (IT basics)
  │   │      🔥 Demand: ⭐⭐⭐⭐ (Computer literacy = everywhere)
  │   │
  │   └── Electronics Mechanic
  │          ⏱️  2 saal | 💰 ₹2-5K/yr | 💼 ₹1.5-3L/yr | 📈 ₹4-8L/yr
  │
  └── 📝 NON-ENGINEERING TRADES
      │
      ├── Stenography (English / Hindi)
      │      ⏱️  1 saal | 💰 ₹2-5K | 💼 ₹2-3L/yr | 📈 Govt steno: ₹4-8L/yr
      │      🔥 Court/Govt offices mein permanent demand
      │
      ├── Sewing Technology / Cutting & Tailoring
      │      ⏱️  1 saal | 💰 ₹2-5K | 💼 ₹1.5-2.5L/yr
      │      📈 Own boutique: ₹5-15L/yr
      │
      ├── Hair & Skin Care (Beautician)
      │      ⏱️  1 saal | 💰 ₹2-5K | 💼 ₹1.5-3L/yr
      │      📈 Own salon: ₹8-25L/yr (metro = ₹30L+)
      │      🔥 Demand: ⭐⭐⭐⭐⭐ (Beauty industry booming!)
      │
      ├── Photography
      │      ⏱️  1 saal | 💰 ₹2-5K | 💼 ₹2-4L/yr
      │      📈 Wedding photographer: ₹10-30L/yr
      │
      ├── Hospital Housekeeping
      │      ⏱️  1 saal | 💰 ₹2-5K | 💼 ₹1.5-2.5L/yr
      │
      └── Desktop Publishing (DTP)
             ⏱️  1 saal | 💰 ₹2-5K | 💼 ₹1.5-3L/yr | 📈 ₹3-6L/yr
""")



def print_section_4_defence():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎖️  SECTION 4: DEFENCE & GOVERNMENT JOBS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⭐ FREE training + salary during training
  ⭐ Job security = lifetime
  ⭐ Pension + Healthcare + Housing + Respect

  │
  ├── 🪖 SEEDHA 10th KE BAAD DEFENCE
  │   │
  │   ├── Indian Army — Agniveer (General Duty)
  │   │      ⏱️  4 saal contract | Age: 17.5-21
  │   │      💰 FREE (salary milti training mein bhi!)
  │   │      💼 ₹30,000/month starting → ₹40,000/month 4th year
  │   │      📈 Permanent hone pe: ₹50K-1L/month + perks
  │   │      🎯 Agniveer Rally + Physical + Written + Medical
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   ├── Indian Army — Tradesman / Clerk / Technical
  │   │      ⏱️  4 saal (Agniveer) | 💰 FREE
  │   │      💼 ₹30-40K/month | 📈 After permanent: ₹60K-1.2L/month
  │   │
  │   ├── Indian Navy — Agniveer (SSR / MR)
  │   │      ⏱️  4 saal | 💰 FREE + stipend
  │   │      💼 ₹30-40K/month | 📈 Permanent: ₹60K-1.5L/month
  │   │      🎯 Navy entrance + Physical + Medical
  │   │      🔥 Ships pe duniya ghum! 🌊
  │   │
  │   ├── Indian Air Force — Agniveer (Group X & Y)
  │   │      ⏱️  4 saal | 💰 FREE
  │   │      💼 ₹30-40K/month | 📈 ₹60K-1.5L/month
  │   │      🎯 STAR (Airmen Selection Test)
  │   │
  │   ├── Coast Guard (Navik / Yantrik)
  │   │      ⏱️  4 saal | 💰 FREE
  │   │      💼 ₹30-40K/month | 📈 ₹60K-1.2L/month
  │   │
  │   ├── BSF / CRPF / CISF / SSB / ITBP (Constable)
  │   │      ⏱️  Training: 9-12 months | 💰 FREE
  │   │      💼 ₹25-35K/month | 📈 Inspector: ₹50-80K/month
  │   │      🎯 SSC GD Constable exam
  │   │
  │   ├── State Police Constable
  │   │      ⏱️  Training: 6-9 months | 💰 FREE
  │   │      💼 ₹20-30K/month | 📈 SI/Inspector: ₹40-70K/month
  │   │      🎯 State Police exam
  │   │
  │   └── Railway Group D
  │          ⏱️  Permanent job | 💰 FREE
  │          💼 ₹20-25K/month | 📈 Senior: ₹35-50K/month
  │          🎯 RRB Group D exam
  │          🔥 Demand: ⭐⭐⭐⭐ (Lakhs apply but jobs bhi lakhs!)
  │
  ├── 🎖️  12th KE BAAD DEFENCE (Officer Level!)
  │   │
  │   ├── NDA (National Defence Academy) — Officer banna!
  │   │      ⏱️  3 yrs NDA + 1 yr IMA/AFA/INA = 4 saal
  │   │      💰 FREE + ₹56,000/month stipend during training!
  │   │      🎯 UPSC NDA exam (after 12th) + SSB Interview (5 days)
  │   │      💼 Lieutenant: ₹70-80K/month
  │   │      📈 Colonel: ₹2-2.5L/month | General: ₹3L+ + perks worth crores
  │   │      🏫 NDA Khadakwasla, Pune
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Ultimate respect + power + lifestyle)
  │   │      ⚠️  Very tough: 4-5 lakh attempt, ~400 selected!
  │   │
  │   └── Technical Entry Scheme (TES — 10+2)
  │          ⏱️  4 yrs (direct officer after 12th PCM)
  │          💰 FREE + stipend
  │          💼 Same as NDA officers
  │
  └── 📋 OTHER GOVT EXAMS (Age 18+, after 12th)
      │
      ├── SSC CHSL (12th pass — LDC/DEO/PA)
      │      💼 ₹25-35K/month | 📈 ₹50-70K/month | 🔥 Lakhs of posts!
      │
      ├── SSC MTS (10th pass — Multi Tasking Staff)
      │      💼 ₹18-22K/month | 📈 ₹30-40K/month
      │
      ├── Bank Clerk (SBI/IBPS)
      │      💼 ₹25-30K/month | 📈 Manager: ₹60K-1L/month
      │      🎯 IBPS Clerk / SBI Clerk | 🔥 Demand: ⭐⭐⭐⭐
      │
      ├── Bank PO (Probationary Officer)
      │      💼 ₹45-55K/month | 📈 AGM/DGM: ₹1.5-2.5L/month
      │      🎯 IBPS PO / SBI PO (graduation needed)
      │
      └── State Govt Jobs (Patwari, Lekhpal, Gram Sevak etc.)
             💼 ₹20-30K/month | 📈 ₹40-60K/month
             🔥 Rural India mein bahut respect!
""")



def print_section_5_vocational():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 SECTION 5: VOCATIONAL & SHORT-TERM COURSES (Jaldi skill = Jaldi paisa)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⭐ 3 months se 1 saal mein course khatam
  ⭐ Seedha kaam pe lag jao ya khud ka business start karo
  ⭐ Investment kam, return fast!

  │
  ├── 💇 BEAUTY & WELLNESS
  │   │
  │   ├── Beautician / Cosmetology Course
  │   │      ⏱️  3-6 months | 💰 ₹20K-1L
  │   │      💼 ₹1.5-3L/yr | 📈 Own salon: ₹10-30L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (₹1 lakh crore industry India mein!)
  │   │
  │   ├── Spa Therapy / Massage Therapy
  │   │      ⏱️  3-6 months | 💰 ₹30-80K
  │   │      💼 ₹2-4L/yr | 📈 5-star spa: ₹8-15L/yr
  │   │
  │   └── Makeup Artist Course
  │          ⏱️  1-3 months | 💰 ₹20K-1L
  │          💼 Bridal makeup: ₹10-50K per event!
  │          📈 Celebrity MUA: ₹30-80L/yr
  │          🔥 Demand: ⭐⭐⭐⭐⭐ (Weddings = ₹5 lakh crore industry!)
  │
  ├── 💻 IT & COMPUTER COURSES
  │   │
  │   ├── DCA (Diploma in Computer Applications)
  │   │      ⏱️  6 months-1 yr | 💰 ₹10-30K
  │   │      💼 ₹1.5-3L/yr | 📈 ₹4-8L/yr
  │   │
  │   ├── Web Development (Full Stack)
  │   │      ⏱️  3-6 months (bootcamp) | 💰 ₹30K-2L
  │   │      💼 ₹4-8L/yr | 📈 Senior dev: ₹15-40L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (FAANG ke bina bhi coding = paisa!)
  │   │
  │   ├── Digital Marketing
  │   │      ⏱️  3-6 months | 💰 ₹20K-1L
  │   │      💼 ₹3-6L/yr | 📈 Own agency: ₹20-50L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   ├── Tally / Accounting Software (GST)
  │   │      ⏱️  1-3 months | 💰 ₹5-15K
  │   │      💼 ₹1.5-3L/yr | 📈 ₹4-8L/yr (accountant)
  │   │      🔥 Demand: ⭐⭐⭐⭐ (GST ke baad har shop ko Tally chahiye)
  │   │
  │   ├── Ethical Hacking / Cybersecurity
  │   │      ⏱️  3-6 months | 💰 ₹50K-2L
  │   │      💼 ₹4-8L/yr | 📈 ₹15-50L/yr (bug bounty = lakhs extra!)
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐
  │   │
  │   ├── Mobile Repairing
  │   │      ⏱️  1-3 months | 💰 ₹5-20K
  │   │      💼 Own shop: ₹2-5L/yr | 📈 ₹5-12L/yr (busy area)
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (100 crore smartphones India mein!)
  │   │
  │   ├── Hardware & Networking (CCNA)
  │   │      ⏱️  3-6 months | 💰 ₹20-60K
  │   │      💼 ₹2.5-4L/yr | 📈 Network Engineer: ₹8-20L/yr
  │   │
  │   └── App Development (Android/iOS)
  │          ⏱️  3-6 months | 💰 ₹30K-1.5L
  │          💼 ₹4-8L/yr | 📈 Senior: ₹15-35L/yr | Freelance: ₹20-50L/yr
  │          🔥 Demand: ⭐⭐⭐⭐⭐
  │
  ├── 🎬 MEDIA & ENTERTAINMENT
  │   │
  │   ├── Video Editing (Premiere Pro / DaVinci)
  │   │      ⏱️  1-3 months | 💰 ₹10-50K
  │   │      💼 ₹3-5L/yr | 📈 YouTube editor: ₹8-20L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Content = king, editor = PM)
  │   │
  │   ├── Acting / Theatre Course
  │   │      ⏱️  1-3 saal | 💰 ₹50K-5L
  │   │      💼 ₹1-5L/yr (struggling) | 📈 Famous: UNLIMITED 🤑
  │   │      🏫 NSD Delhi, FTII Pune, Barry John
  │   │
  │   ├── Sound Engineering / Music Production
  │   │      ⏱️  6 months-1 yr | 💰 ₹50K-3L
  │   │      💼 ₹3-5L/yr | 📈 Top producer: ₹20-50L/yr
  │   │
  │   ├── Radio Jockey (RJ) / Anchoring
  │   │      ⏱️  3-6 months | 💰 ₹20-80K
  │   │      💼 ₹2-4L/yr | 📈 Famous RJ: ₹15-40L/yr
  │   │
  │   └── YouTube / Content Creation (Self-taught mostly)
  │          ⏱️  Khud seekho + 6-12 months consistency
  │          💰 Almost FREE (phone + internet)
  │          💼 ₹0 (pehle 6 months) | 📈 Popular: ₹5-50L/month! 🤑
  │          🔥 Demand: ⭐⭐⭐⭐⭐ (Ek achha channel = lifetime income)
  │
  ├── 🚗 AUTOMOBILE & DRIVING
  │   │
  │   ├── Driving (LMV/HMV License + Commercial)
  │   │      ⏱️  1-3 months | 💰 ₹5-15K
  │   │      💼 Cab driver: ₹2-4L/yr | Truck: ₹3-6L/yr
  │   │      📈 Ola/Uber top: ₹5-8L/yr | Own fleet: ₹15-30L/yr
  │   │
  │   └── Auto Mechanic / EV Technician
  │          ⏱️  3-6 months | 💰 ₹10-30K
  │          💼 ₹2-3L/yr | 📈 EV specialist: ₹5-12L/yr
  │          🔥 Demand: ⭐⭐⭐⭐⭐ (EV = future = shortage of technicians)
  │
  └── 🍳 FOOD & HOSPITALITY
      │
      ├── Bakery & Pastry Course
      │      ⏱️  1-3 months | 💰 ₹20-60K
      │      💼 ₹1.5-3L/yr | 📈 Own bakery: ₹8-25L/yr
      │
      ├── Chef / Cooking Course
      │      ⏱️  3-6 months | 💰 ₹30K-2L
      │      💼 ₹2-4L/yr | 📈 5-star chef: ₹15-35L/yr
      │
      └── Cafe / Restaurant Management
             ⏱️  3-6 months | 💰 ₹20-50K
             💼 ₹2-3L/yr | 📈 Own cafe: ₹8-25L/yr
""")



def print_section_6_open_school():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📖 SECTION 6: OPEN SCHOOLING & DISTANCE LEARNING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⭐ Regular school nahi ja sakte? Koi baat nahi!
  ⭐ Ghar baith ke padho, valid certificate milega
  ⭐ Kaam ke saath padhai possible!

  │
  ├── 📚 NIOS (National Institute of Open Schooling)
  │      ⏱️  Apni speed se (1-5 saal mein 12th complete)
  │      💰 ₹2-5K (total — bahut sasta!)
  │      🎯 Koi entrance nahi — seedha admission
  │      ✅ NIOS 12th = Regular 12th ke barabar valid!
  │      ✅ NEET, JEE, UPSC sab de sakte ho NIOS se!
  │      🔥 Best for: Working students, repeaters, dropouts
  │
  ├── 📚 State Open Schools (MPSOS, BBOSE, KSOS etc.)
  │      ⏱️  1-2 saal | 💰 ₹1-3K | Same as NIOS but state level
  │
  └── 🎓 IGNOU (Indira Gandhi National Open University)
         ⏱️  Varies (6 months - 3 yrs)
         💰 ₹5K-20K (cheapest university in India!)
         ✅ UGC approved — valid everywhere
         ✅ 10th ke baad bhi kuch diploma courses available
         ✅ BA, B.Com, BCA sab distance se kar sakte!
         🔥 Demand: ⭐⭐⭐⭐ (Kaam karte hue degree = smart move)
""")



def print_section_7_sports_entrepreneurship():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏆 SECTION 7: SPORTS, FITNESS & ENTREPRENEURSHIP
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ├── ⚽ SPORTS & FITNESS PATH
  │   │
  │   ├── 🏏 Cricket Academy (State/Private)
  │   │      ⏱️  3-8 saal continuous training (bachpan se shuru karo!)
  │   │      💰 ₹50K-5L/yr (coaching fees)
  │   │      💼 Ranji: ₹5-15L/yr | IPL: ₹50L-16 Crore/yr! 🤑
  │   │      📈 International: ₹5-15 Crore/yr + endorsements
  │   │      🔥 India ka sabse glamorous career (if talent + luck hai)
  │   │
  │   ├── ⚽ Football / Hockey / Athletics Academy
  │   │      ⏱️  5-10 saal training
  │   │      💰 SAI: FREE | Pvt: ₹1-5L/yr
  │   │      💼 ISL player: ₹20-80L/yr | National: ₹5-15L/yr
  │   │      📈 International: ₹1-10 Crore/yr
  │   │
  │   ├── 🥊 Wrestling / Boxing / Shooting / Weightlifting
  │   │      ⏱️  5-8 saal | 💰 SAI: FREE | Pvt: ₹50K-3L/yr
  │   │      💼 National medalist: ₹5-10L/yr
  │   │      📈 Olympic medal: ₹5-10 Crore prize + lifetime pension!
  │   │
  │   ├── 🏋️ Gym / Personal Trainer Certification
  │   │      ⏱️  3-6 months | 💰 ₹20K-1L (ACE, NSCA certs)
  │   │      💼 ₹2-5L/yr | 📈 Celebrity trainer: ₹20-60L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (Fitness obsession growing!)
  │   │
  │   ├── 🧘 Yoga Instructor
  │   │      ⏱️  3-12 months (200hr/500hr teacher training)
  │   │      💰 ₹20K-2L | 💼 ₹2-5L/yr
  │   │      📈 Online yoga: ₹10-30L/yr | International: ₹30-60L/yr
  │   │      🔥 Demand: ⭐⭐⭐⭐⭐ (International Yoga Day ke baad BOOM!)
  │   │
  │   └── 🎓 B.P.Ed (Physical Education Degree)
  │          ⏱️  4 saal (integrated) / 2 yrs (after grad)
  │          💰 ₹20-80K/yr (Govt) | 💼 ₹3-5L/yr
  │          📈 Govt PE Teacher: ₹6-12L/yr
  │
  └── 💡 ENTREPRENEURSHIP / SELF-EMPLOYMENT (Apna Boss Khud!)
      │
      ├── 🏪 Family Business Join Karo
      │      ⏱️  Immediately start | 💰 Depends on business
      │      💼 Whatever family earns | 📈 Scale up = unlimited!
      │      🔥 Pro tip: Business + Degree = Best combo
      │
      ├── 💻 Freelancing (Coding / Design / Writing / Video Edit)
      │      ⏱️  Learn: 3-6 months | Start earning: 1-3 months
      │      💰 ₹0-50K (laptop + internet + skills)
      │      💼 Starting: ₹3-8L/yr | 📈 Top freelancer: ₹20-80L/yr
      │      🔥 Demand: ⭐⭐⭐⭐⭐ (Fiverr, Upwork, Toptal — global clients!)
      │
      ├── 📱 E-commerce / Dropshipping
      │      ⏱️  1-3 months setup | 💰 ₹10-50K start
      │      💼 ₹2-5L/yr (starting) | 📈 ₹20-50L/yr (scaled)
      │      🔥 Amazon, Flipkart, Meesho seller = low risk
      │
      ├── 🎥 YouTube / Instagram / Blogging
      │      ⏱️  6 months minimum (consistency chahiye!)
      │      💰 Phone + Internet = ₹0 extra
      │      💼 Monetization: ₹5K-50K/month (1-2 yrs)
      │      📈 Popular: ₹5L-50L/MONTH! (sponsorships + AdSense)
      │      🔥 Demand: ⭐⭐⭐⭐⭐ (Creator economy = ₹50,000 Crore India)
      │
      ├── 🌾 Agriculture / Dairy / Poultry / Fishery
      │      ⏱️  6 months learning + start
      │      💰 ₹50K-5L (land + equipment) | MUDRA loan available
      │      💼 ₹2-5L/yr | 📈 Commercial farming: ₹10-50L/yr
      │      🔥 Govt schemes: PM-KISAN, KCC, NABARD subsidy
      │
      ├── 🏗️  Small Business with Govt Help
      │   │
      │   ├── PMKVY (Skill India — Free training + certificate)
      │   │      ⏱️  1-6 months | 💰 FREE! (Govt pays)
      │   │      💼 Placement support dete hain
      │   │
      │   ├── MUDRA Loan (₹50K-10L loan without collateral!)
      │   │      Business ideas: Chai tapri, salon, kirana, mobile shop,
      │   │      tailoring, food stall, auto garage, tiffin service
      │   │
      │   └── Startup India (₹10L-1Cr funding for ideas)
      │          Tax benefits + easy registration + mentorship
      │
      └── 🔧 Skilled Trades (High earning, low investment)
          │
          ├── AC/Fridge Repair → ₹3-10L/yr (summer mein ₹50K/month!)
          ├── Mobile Repair Shop → ₹3-8L/yr
          ├── Electrical Contractor → ₹5-20L/yr
          ├── Plumbing Business → ₹3-10L/yr
          ├── Car Detailing/Washing → ₹3-8L/yr
          ├── Tiffin Service → ₹3-12L/yr
          └── Xerox/Print Shop → ₹2-6L/yr
""")



def print_comparison_tables():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 QUICK COMPARISON TABLES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

┌──────────────────────────────────────────────────────────────────────────────────────┐
│ 💰 TOP 10 HIGHEST PAYING CAREERS (Salary ke basis pe rank)                           │
├────┬──────────────────────────────┬──────────────────┬───────────────────────────────┤
│ #  │ Career                       │ Time to Get There │ Peak Salary                   │
├────┼──────────────────────────────┼──────────────────┼───────────────────────────────┤
│ 1  │ 🖥️  Software/AI Engineer     │ 4-5 saal         │ ₹50L-2Cr/yr (FAANG)          │
│ 2  │ 👨‍⚕️ Doctor (Super-Specialist) │ 10-12 saal       │ ₹1-5 Cr/yr                   │
│ 3  │ ⚖️  Corporate Lawyer          │ 5-8 saal         │ ₹50L-3Cr/yr                  │
│ 4  │ 📊 CA (Chartered Accountant) │ 5-6 saal         │ ₹25L-2Cr/yr                  │
│ 5  │ 💹 Investment Banker/CFA     │ 6-8 saal         │ ₹50L-3Cr/yr                  │
│ 6  │ ✈️  Pilot (Captain)           │ 5-8 saal         │ ₹50L-1.5Cr/yr               │
│ 7  │ 🚢 Merchant Navy Captain     │ 8-10 saal        │ ₹80L-1.5Cr/yr (tax-free!)   │
│ 8  │ 🏛️  IAS/IPS Officer           │ 5-8 saal         │ ₹20-30L/yr + perks (₹1Cr+)  │
│ 9  │ 🎨 UX/Product Designer       │ 4-6 saal         │ ₹30-80L/yr                   │
│ 10 │ 🎥 YouTuber/Creator (Top)    │ 2-5 saal         │ ₹1-10Cr/yr                   │
└────┴──────────────────────────────┴──────────────────┴───────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────┐
│ ⏱️  FASTEST EARNING PATHS (Jaldi paisa chahiye?)                                     │
├────┬───────────────────────────────┬──────────┬────────────────────────────────────── │
│ #  │ Path                          │ Time     │ Expected Earning                      │
├────┼───────────────────────────────┼──────────┼───────────────────────────────────────┤
│ 1  │ ITI (Electrician/AC mechanic) │ 1-2 saal │ ₹1.5-3L/yr (own biz: ₹5-15L)       │
│ 2  │ D.Pharma → Medical Shop      │ 2 saal   │ ₹8-20L/yr (own shop profit!)        │
│ 3  │ Mobile Repair                 │ 1-3 month│ ₹2-5L/yr                            │
│ 4  │ Digital Marketing             │ 3-6 month│ ₹3-6L/yr (freelance = more)         │
│ 5  │ Web Development Bootcamp      │ 3-6 month│ ₹4-8L/yr                            │
│ 6  │ Beauty/Salon Course           │ 3-6 month│ ₹3-10L/yr (own salon fast!)         │
│ 7  │ Tally + Accounting            │ 1-3 month│ ₹1.5-3L/yr                          │
│ 8  │ Video Editing                 │ 1-3 month│ ₹3-5L/yr (freelance: ₹8L+)         │
│ 9  │ Driving (Ola/Uber/Truck)      │ 1 month  │ ₹2-5L/yr                            │
│ 10 │ Army Agniveer                 │ 0 (join!)│ ₹3.6L/yr + free food/stay           │
└────┴───────────────────────────────┴──────────┴───────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────┐
│ 🔥 TOP 10 FUTURE-PROOF CAREERS (2025-2035 ke liye best)                              │
├────┬─────────────────────────────────────┬───────────────────────────────────────────┤
│ #  │ Career                              │ Why Future-Proof?                         │
├────┼─────────────────────────────────────┼───────────────────────────────────────────┤
│ 1  │ AI / Machine Learning Engineer      │ Har industry mein AI lag raha             │
│ 2  │ Data Scientist                      │ Data = new oil                            │
│ 3  │ Cybersecurity Expert                │ Jitna digital = utna cyber crime          │
│ 4  │ Electric Vehicle (EV) Engineer      │ Petrol khatam, EV aayega                 │
│ 5  │ UX/UI Designer                      │ Har app/website ko designer chahiye       │
│ 6  │ Healthcare (Nursing/Doctor)         │ Log beemar hote rahenge — job hamesha     │
│ 7  │ Renewable Energy Engineer           │ Solar/Wind = future ka power source       │
│ 8  │ Content Creator / Digital Marketing │ Online shopping = online marketing        │
│ 9  │ Blockchain Developer                │ Crypto + DeFi + Web3                     │
│ 10 │ Robotics & Automation               │ Factories mein robots replace karenge     │
└────┴─────────────────────────────────────┴───────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────┐
│ 💰 CHEAPEST COURSES (Paise nahi hain? Tension mat le!)                               │
├────┬─────────────────────────────────┬──────────┬────────────────────────────────────┤
│ #  │ Course                          │ Total Fee│ Earning Potential                    │
├────┼─────────────────────────────────┼──────────┼────────────────────────────────────┤
│ 1  │ Govt ITI                        │ ₹2-10K  │ ₹1.5-15L/yr                        │
│ 2  │ NIOS (Open School 12th)         │ ₹2-5K   │ Sab kuch possible baad mein!       │
│ 3  │ Govt Polytechnic Diploma        │ ₹15-40K │ ₹2-15L/yr (after lateral entry)    │
│ 4  │ PMKVY (Skill India)             │ FREE!   │ ₹1.5-4L/yr                        │
│ 5  │ Army/Navy/Air Force             │ FREE!   │ ₹3.6-18L/yr + perks               │
│ 6  │ CA Foundation                   │ ₹10-15K │ ₹7L-2Cr/yr (after clearing!)      │
│ 7  │ IGNOU Diploma/Degree            │ ₹5-20K  │ Degree value same as regular!      │
│ 8  │ Govt B.Sc/BA/B.Com              │ ₹10-50K │ ₹3-8L/yr                          │
│ 9  │ YouTube/Content Creation        │ ₹0      │ ₹0-10Cr/yr (sky = limit!)         │
│ 10 │ Mobile Repair (self-taught)     │ ₹5-10K  │ ₹2-8L/yr                          │
└────┴─────────────────────────────────┴──────────┴────────────────────────────────────┘
""")



def print_decision_guide():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🧭 DECISION GUIDE — TU KYA BANNA CHAHTA HAI?
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

┌────────────────────────────────────────────────────────────────────────────────────┐
│  GOAL                          →  PATH                                             │
├────────────────────────────────────────────────────────────────────────────────────┤
│  🖥️  Software Engineer banna    →  PCM → JEE → B.Tech CSE (IIT/NIT)              │
│  👨‍⚕️ Doctor banna               →  PCB → NEET → MBBS                              │
│  💰 Bahut paisa chahiye (fast) →  Commerce → CA / PCM → B.Tech CSE               │
│  🏛️  IAS/IPS banna              →  Any stream → Graduation → UPSC                 │
│  ⚖️  Lawyer banna               →  BA-LLB / BBA-LLB (5 yr NLU)                   │
│  🪖 Fauji banna                →  NDA (12th ke baad) / Agniveer (10th ke baad)   │
│  ✈️  Pilot banna                →  PCM → 12th → CPL training (₹35L!)             │
│  🎨 Designer banna             →  NID/NIFT/UCEED → B.Des                         │
│  🎬 Actor banna                →  NSD/FTII ya direct industry try                │
│  📺 YouTuber banna             →  Start NOW + consistency                         │
│  🏏 Cricketer banna            →  Academy join (jitna jaldi utna better)         │
│  👩‍🏫 Teacher banna              →  Any stream → Graduation → B.Ed                 │
│  🏥 Nurse banna (abroad jaana) →  PCB → B.Sc Nursing / GNM                      │
│  💊 Pharmacist banna           →  D.Pharma (2yr) / B.Pharma (4yr) → Own shop    │
│  🏠 Interior Designer banna    →  12th → NID / Private institute                 │
│  🔧 Jaldi kamana hai           →  ITI / Diploma / Vocational courses             │
│  💻 Coding seekh ke kamana     →  Online bootcamp (3-6 months) → Freelance/Job   │
│  🌾 Farming mein paisa banana  →  Agriculture diploma + Govt schemes             │
│  🚢 Duniya ghumna + paisa     →  Merchant Navy / Pilot / Tourism                │
└────────────────────────────────────────────────────────────────────────────────────┘


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💡 IMPORTANT TIPS (Ye mat bhoolna bhai!)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1️⃣  INTEREST > Everything
      → Jis cheez mein maza aaye wohi karo. Force mein kiya = failure

  2️⃣  FAMILY SITUATION matter karti hai
      → Agar paise ki dikkat → ITI/Diploma/Govt college = smart choice
      → Agar afford kar sakte → Take your time, aim high

  3️⃣  SKILLS > DEGREE (aaj ke time mein)
      → ₹20L package wala coder > ₹3L job wala engineer
      → Skills seekho chahe degree koi bhi ho

  4️⃣  DOSTO KO FOLLOW MAT KARO
      → Tera career = TERA. Dost PCM le raha toh tu bhi PCM? WRONG!

  5️⃣  BACKUP PLAN rakho hamesha
      → CA nahi hua? B.Com degree toh hai! MBA kar lo!
      → NEET nahi clear? B.Sc Nursing, BPT, B.Pharma bhi achhe!

  6️⃣  GOVT vs PRIVATE college
      → Govt = Sasta + Better placements (IIT, NIT, AIIMS, NLU)
      → Private = Expensive but seat easy to get
      → Always TRY for Govt first!

  7️⃣  ONLINE RESOURCES (Free seekhne ke liye)
      → YouTube (free courses for everything)
      → Coursera, edX (free audit mode)
      → freeCodeCamp (coding)
      → Khan Academy (basics)
      → NPTEL/SWAYAM (Govt free courses with certificate!)

  8️⃣  SALARY IS NOT EVERYTHING
      → Work-life balance bhi dekho
      → Doctor: ₹1Cr salary but 80hr/week kaam
      → Govt job: ₹6L salary but tension-free life + pension

  9️⃣  MULTIPLE PATHS EXIST
      → 10th → ITI → Diploma → B.Tech → M.Tech (step by step bhi ho sakta!)
      → 10th → 12th Arts → Law → Corporate Lawyer (₹50L+)
      → 10th → Fail? → NIOS → Still IIT/AIIMS possible!

  🔟 AGE KI LIMIT MAT SOCHO
      → CA 21 mein bhi clear kar sakte, 30 mein bhi
      → UPSC 21-32 years attempt kar sakte
      → Coding 15 mein bhi seekh sakte, 40 mein bhi
""")



def print_footer():
    print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📌 DISCLAIMER & NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  • Salary figures are approximate (2024-25 data) and vary by:
    → City (Mumbai/Bangalore = 2x of small city)
    → College tier (IIT vs Tier-3)
    → Skills & performance
    → Luck & connections (networking matters!)

  • Fees are approximate ranges:
    → Govt = Government/aided colleges
    → Pvt = Private unaided colleges

  • "Starting salary" = first job after completing the course
  • "Experienced salary" = after 5-10 years of work experience

  • Sources: NIRF Rankings, Glassdoor India, PayScale India,
    NCS Portal, official college websites, MHRD data

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ╔══════════════════════════════════════════════════════════════════╗
  ║  Made with ❤️  by Krishna1k                                     ║
  ║  Generated by Kiro AI Assistant                                 ║
  ║  Share karo apne dosto ke saath — sabko help hogi!              ║
  ╚══════════════════════════════════════════════════════════════════╝
""")


# ════════════════════════════════════════════════════════════════════════
# MAIN EXECUTION — Run karo toh pura tree print hoga!
# ════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print_header()
    print_main_tree()
    print_section_1_science()
    print_section_1_science_continued()
    print_section_1_pcb()
    print_section_1_commerce()
    print_section_1_arts()
    print_section_2_diploma()
    print_section_3_iti()
    print_section_4_defence()
    print_section_5_vocational()
    print_section_6_open_school()
    print_section_7_sports_entrepreneurship()
    print_comparison_tables()
    print_decision_guide()
    print_footer()

    print("\n\n✅ Pura career tree print ho gaya! Ab decision le aur mehnat kar! 💪🔥\n")
