"""
Pure-Python PDF generator for Class 10 Maths Chapter 2: Polynomials.
No external libraries required.

Generates: Class10_Maths_Ch2_Polynomials.pdf
"""

import re
import zlib
from pathlib import Path


# ---------- Content ----------
CONTENT = r"""
CLASS 10 NCERT MATHS
CHAPTER 2: POLYNOMIALS
==========================================

A simplified, detailed guide in Hinglish
For students who missed Class 7-8-9
Based on the official NCERT English Medium textbook
==========================================


==========================================
SECTION 1: FOUNDATION (Algebra ki ABCD)
==========================================


1.1 VARIABLE KYA HOTA HAI?
--------------------------

   VARIABLE = ek alphabet (jaise x, y, z) jo kisi
   UNKNOWN number ko represent karta hai.

   EXAMPLE:
     Maan le tere paas kuch chocolates hain, par tu
     count nahi jaanta. Tu kahega "x chocolates hain
     mere paas". Yahan x variable hai.


1.2 CONSTANT KYA HOTA HAI?
--------------------------

   CONSTANT = jiska value FIXED ho.
   Numbers like 5, -3, 1/2, pi - sab constant hain.


1.3 ALGEBRAIC EXPRESSION
------------------------

   EXPRESSION = variable + constant + operations
   (+, -, x, /) ka mixture.

   EXAMPLES:
     - 2x + 5        (variable x, constants 2 and 5)
     - 3x^2 - 7x + 1
     - 5y + 3


1.4 POLYNOMIAL - ASLI DEFINITION
--------------------------------

   POLYNOMIAL = ek special type ka algebraic
   expression jisme:
     - Variable ke power WHOLE NUMBERS (0,1,2,3...) ho
     - Power NEGATIVE ya FRACTION nahi ho


   POLYNOMIAL HAI:
     - 2x + 3         (power 1)
     - x^2 - 5x + 6   (power 2)
     - 7              (constant, power 0)


   POLYNOMIAL NAHI HAI:
     - x^(-2) + 3     (negative power)
     - sqrt(x) + 1    (= x^(1/2), fraction power)
     - 1/x            (= x^(-1), negative power)


1.5 DEGREE OF POLYNOMIAL
------------------------

   DEGREE = polynomial mein HIGHEST power of variable.

   EXAMPLES:
     Polynomial            Highest Power   Degree
     ------------------    -------------   ------
     2x + 5                  1               1
     3x^2 - 7x + 1           2               2
     x^3 + 2x^2 - x + 4      3               3
     7                       0               0


1.6 TYPES OF POLYNOMIALS (degree ke hisab se)
---------------------------------------------

   Degree   Naam                  Form              Example
   ------   --------------------  ----------------  ----------------
   0        Constant Polynomial   c                 5, -3, 7
   1        LINEAR Polynomial     ax + b            2x + 3
   2        QUADRATIC Polynomial  ax^2 + bx + c     x^2 - 5x + 6
   3        CUBIC Polynomial      ax^3 + bx^2 +     x^3 - 2x + 1
                                  cx + d


   IMPORTANT: a != 0 hona chahiye (warna degree
   change ho jayegi).


1.7 ZERO / ROOT OF A POLYNOMIAL
-------------------------------

   ZERO = wo value of x jiske liye polynomial ki
   value 0 ho jaye.

   EASY WAY TO FIND:
     p(x) = 0 set karo aur x solve karo.


   EXAMPLE: p(x) = 2x - 6 ka zero nikaal

     2x - 6 = 0
     2x = 6
     x = 3

   So zero = 3.

   CHECK: p(3) = 2(3) - 6 = 6 - 6 = 0. Sahi!


==========================================
Q AND A TIME - SECTION 1 KA TEST
==========================================


   Q1. In mein se POLYNOMIAL konse hain? (Yes/No)
       (a) 3x^2 + 5x - 2
       (b) 2x^(-1) + 4
       (c) sqrt(x) + 3
       (d) 7x^3 - x + 1
       (e) 5


   Q2. Inka DEGREE bata:
       (a) 4x^5 + 3x^2 - 1
       (b) 7x + 2
       (c) 9


   Q3. p(x) = 5x^3 - 2x^2 + 7x - 1 polynomial ka
       type kya hai?
       (Linear / Quadratic / Cubic)


   Q4. p(x) = 3x + 9 ka zero nikaal.


   Q5. Agar p(x) = x^2 - 4, toh:
       (a) p(2) ki value kya hai?
       (b) p(-2) ki value kya hai?
       (c) Inn jawabon se kya conclusion nikalta hai?


==========================================
PROGRESS STATUS
==========================================

   [DONE]   Section 1: Foundation
   [TO DO]  Section 2: Geometrical Meaning of Zeroes
   [TO DO]  Section 3: Relationship between Zeroes
            and Coefficients
   [TO DO]  Practice Problems
   [TO DO]  Summary

   (Aage ke sections aate jayenge as we progress
    chapter mein.)


==========================================
Generated by Kiro for Krishna1k
Class 10 NCERT Maths - Chapter 2: Polynomials
==========================================
"""


# ---------- PDF builder ----------

PAGE_W, PAGE_H = 595, 842
MARGIN_L, MARGIN_R = 50, 50
MARGIN_T, MARGIN_B = 60, 50
LINE_HEIGHT = 13
FONT_SIZE = 10
HEADER_FONT_SIZE = 14
TITLE_FONT_SIZE = 20


def escape_pdf_text(s: str) -> str:
    s = s.replace("\\", "\\\\")
    s = s.replace("(", "\\(").replace(")", "\\)")
    s = re.sub(r"[^\x20-\x7E]", "", s)
    return s


def wrap_line(line: str, max_chars: int = 95) -> list[str]:
    if len(line) <= max_chars:
        return [line]
    indent_match = re.match(r"^(\s*)", line)
    indent = indent_match.group(1) if indent_match else ""
    words = line.split(" ")
    out, cur = [], indent
    for w in words:
        if len(cur) + len(w) + 1 > max_chars:
            out.append(cur.rstrip())
            cur = indent + w
        else:
            cur = (cur + " " + w) if cur.strip() else (indent + w)
    if cur.strip():
        out.append(cur.rstrip())
    return out


def build_pages(content: str):
    raw_lines = content.splitlines()
    lines = []
    for ln in raw_lines:
        stripped = ln.strip()
        if stripped.startswith("=========="):
            lines.append(("rule", ""))
        elif (stripped and stripped == stripped.upper() and len(stripped) > 5
                and not stripped.startswith("-") and not stripped.startswith("*")
                and re.match(r"^[A-Z0-9 &/().,'\-:]+$", stripped)):
            lines.append(("header", stripped))
        else:
            for w in wrap_line(ln):
                lines.append(("body", w))

    pages = []
    cur_page = []
    y = PAGE_H - MARGIN_T
    for kind, text in lines:
        size = HEADER_FONT_SIZE if kind == "header" else FONT_SIZE
        lh = LINE_HEIGHT + (4 if kind == "header" else 0)
        if y - lh < MARGIN_B:
            pages.append(cur_page)
            cur_page = []
            y = PAGE_H - MARGIN_T
        cur_page.append((kind, text, y, size))
        y -= lh
    if cur_page:
        pages.append(cur_page)
    return pages


def make_content_stream(page_lines, is_first=False) -> bytes:
    parts = []
    if is_first:
        title = "Class 10 NCERT Maths"
        subtitle = "Chapter 2: Polynomials - Detailed Guide"
        parts.append(
            f"BT /F2 {TITLE_FONT_SIZE} Tf {MARGIN_L} {PAGE_H - MARGIN_T} Td "
            f"({escape_pdf_text(title)}) Tj ET"
        )
        parts.append(
            f"BT /F1 12 Tf {MARGIN_L} {PAGE_H - MARGIN_T - 22} Td "
            f"({escape_pdf_text(subtitle)}) Tj ET"
        )
        parts.append(
            f"{MARGIN_L} {PAGE_H - MARGIN_T - 32} m "
            f"{PAGE_W - MARGIN_R} {PAGE_H - MARGIN_T - 32} l S"
        )

    for kind, text, y, size in page_lines:
        if kind == "rule":
            parts.append(f"{MARGIN_L} {y + 5} m {PAGE_W - MARGIN_R} {y + 5} l S")
            continue
        if not text.strip():
            continue
        font = "/F2" if kind == "header" else "/F1"
        safe = escape_pdf_text(text)
        parts.append(f"BT {font} {size} Tf {MARGIN_L} {y} Td ({safe}) Tj ET")

    return ("\n".join(parts)).encode("latin-1")


def build_pdf(out_path: Path):
    pages = build_pages(CONTENT)

    catalog_num = 1
    pages_num = 2
    font1_num = 3
    font2_num = 4

    page_object_nums = []
    content_object_nums = []
    next_num = 5
    for _ in pages:
        page_object_nums.append(next_num)
        next_num += 1
        content_object_nums.append(next_num)
        next_num += 1

    objects = [None] * (next_num - 1)

    objects[catalog_num - 1] = f"<< /Type /Catalog /Pages {pages_num} 0 R >>".encode()

    kids = " ".join(f"{n} 0 R" for n in page_object_nums)
    objects[pages_num - 1] = (
        f"<< /Type /Pages /Count {len(pages)} /Kids [ {kids} ] >>"
    ).encode()

    objects[font1_num - 1] = (
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
        b"/Encoding /WinAnsiEncoding >>"
    )
    objects[font2_num - 1] = (
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold "
        b"/Encoding /WinAnsiEncoding >>"
    )

    for i, page_lines in enumerate(pages):
        pno = page_object_nums[i]
        cno = content_object_nums[i]
        stream = make_content_stream(page_lines, is_first=(i == 0))
        compressed = zlib.compress(stream)
        objects[cno - 1] = (
            f"<< /Length {len(compressed)} /Filter /FlateDecode >>\nstream\n"
        ).encode() + compressed + b"\nendstream"

        objects[pno - 1] = (
            f"<< /Type /Page /Parent {pages_num} 0 R "
            f"/MediaBox [0 0 {PAGE_W} {PAGE_H}] "
            f"/Resources << /Font << /F1 {font1_num} 0 R "
            f"/F2 {font2_num} 0 R >> >> "
            f"/Contents {cno} 0 R >>"
        ).encode()

    out = bytearray()
    out += b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode()
        out += body
        out += b"\nendobj\n"

    xref_pos = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()

    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root {catalog_num} 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n"
    ).encode()

    out_path.write_bytes(out)
    print(f"Wrote {out_path} ({len(out):,} bytes, {len(pages)} pages)")


if __name__ == "__main__":
    out = Path(__file__).parent / "Class10_Maths_Ch2_Polynomials.pdf"
    build_pdf(out)
